export const envKeys = {
	API_URL: process.env.VITE_API_URL,
	IMAGE_SAS_TOKEN: process.env.VITE_IMAGE_SAS_TOKEN,
	AUTH0_DOMAIN: process.env.VITE_APP_AUTH0_DOMAIN,
	AUTH0_CLIENT_ID: process.env.VITE_APP_AUTH0_CLIENT_ID,
	APP_URL: process.env.VITE_APP_URL,
	WEBSITE_URL: process.env.VITE_WEBSITE_URL,
	QB_APP_ID: process.env.VITE_QB_APP_ID,
	QB_AUTH_KEY: process.env.VITE_QB_AUTH_KEY,
	QB_AUTH_SECRET: process.env.VITE_QB_AUTH_SECRET,
	QB_ACCOUNT_KEY: process.env.VITE_QB_ACCOUNT_KEY,
	FIREBASE_API_KEY: process.env.VITE_FIREBASE_API_KEY,
	FIREBASE_AUTH_DOMAIN: process.env.VITE_FIREBASE_AUTH_DOMAIN,
	FIREBASE_PROJECT_ID: process.env.VITE_FIREBASE_PROJECT_ID,
	FIREBASE_STORAGE_BUCKET: process.env.VITE_FIREBASE_STORAGE_BUCKET,
	FIREBASE_MESSAGING_SENDER_ID: process.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
	FIREBASE_APP_ID: process.env.VITE_FIREBASE_APP_ID,
	FIREBASE_MEASUREMENT_ID: process.env.VITE_FIREBASE_MEASUREMENT_ID,
	FIREBASE_VAPI_KEY: process.env.VITE_FIREBASE_VAPI_KEY,
	COMMUNICATION_SERVICES_ENDPOINT:process.env.VITE_COMMUNICATION_SERVICES_ENDPOINT
};

export default envKeys;
