export const thunkString = {
	getMedia: 'media/getMedia',
	addAddress: 'user/addUserAddress',
	updateAddress: 'user/updateAddress',
	addExperience: 'experience/addExperience',
	deleteExperience: 'experience/deleteExperience',
	addEducation: 'education/addEducation',
	updateEducation: 'education/updateEducation',
	deleteEducation: 'education/deleteEducation',
	addAchievement: 'achievement/addAchievement',
	startChat: 'achievement/startChat',
	updateAchievement: 'achievement/updateAchievement',
	deleteAchievement: 'achievement/deleteAchievement',
	addCertificate: 'certificate/addCertificate',
	updateCertificate: 'certificate/updateCertificate',
	deleteCertificate: 'certificate/deleteCertificate',
	unfollowUser: 'user/unfollowUser',
	getConnections: 'user/getConnections',
	getPublicUser: 'user/getPublicUser',
	deleteProfilePicture: 'media/deleteProfilePicture',
	getCountries: 'supportData/getCountres',
	deactivateAccount: 'user/deactivateAccount',
	getUserByQbId: 'user/getUserByQbId',
	addUserDevice: 'user/addUserDevice',
	updateUserDevice: 'user/updateUserDevice',
	getUserDevices: 'user/getUserDevices',
};
